<RFC> Wasm: Add a DNS over HTTPS backend resolver for wasm
multiformats/go-multiaddr-dns pull request #24
Opened 2020-10-21 07:31 UTC by steamraven

Wasm currently lacks a dns resolver being the browser cannot make normal UDP connections.  This adds a DHS over HTTPS backend resolver to allow things like connecting to the bootstrap servers over WSS using /dnsaddr.

Please let me know if I can improve this

2020-10-26 19:45 UTC, Stebalien commented
I agree supporting DOH would be useful, but this code doesn't look multiaddr specific in any way. I assume someone using DOH would set the multiaddr dns resolver in their code and import their favorite DOH client library (possibly this one).

2020-11-06 19:43 UTC, lidel requested changes
Quick feedback: We should avoid JSON requests. JSON representation is not an official DoH spec.

It may be standardized at one point, but right now, only the binary format defined by [RFC8484](https://tools.ietf.org/html/rfc8484) is future-proof.
To guarantee people can use resolvers other than Google and Cloudflare we should make queries in the binary format.

I wrote some notes in https://github.com/ipfs/js-ipfs/issues/2212, including test endpoints compatible with RFC8484, if you wish to make a vendor-agnostic DoH resolver.

2020-11-13 18:39 UTC, aschmahmann commented
Just to clarify there are 2 action items here:
1) This PR is not spec compliant as @lidel mentioned above
2) This PR is a go-dns-doh resolver having nothing to do with multiaddr, you shouldn't be losing out on anything by just making this a separate repo as it could just be plugged into DefaultResolver here by application code.

2021-04-09 14:50 UTC, lidel commented
Superseded by https://github.com/multiformats/go-multiaddr-dns/pull/26  – @aschmahmann are you able to close this?

2021-04-09 14:51 UTC, closed without merging

2021-04-09 14:54 UTC, aschmahmann commented
@lidel #26 isn't really related here other than adding more configurability to the resolver.

As I mentioned above plugging a DoH resolver into the interfaces should do the job. There is now a spec compliant DoH resolver at https://github.com/libp2p/go-doh-resolver.